---
- name: Add AdoptOpenJDK key
  apt_key:
    url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public

- name: Add AdoptOpenJDK repo
  apt_repository:
    repo: "deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/ {{ ansible_distribution_release }} main"
    filename: openjdk

- name: Install Confluence dependencies
  apt:
    name:
      - adoptopenjdk-8-hotspot
      - fontconfig

- name: Create a unix group
  group:
    name: confluence
    system: true
  notify: Restart confluence service

- name: Create a unix user
  user:
    name: confluence
    group: confluence
    comment: Confluence system user
    shell: /bin/false
    home: /opt/atlassian-confluence
    createhome: no
    system: true
  notify: Restart confluence service

- name: Create data directories
  file:
    path: "{{ item }}"
    state: directory
    owner: confluence
    group: confluence
    mode: 0770
  with_items:
    - /var/lib/catalina/temp
    - /var/lib/confluence
    - /var/log/confluence
  notify: Restart confluence service

- include_tasks: install.yml

- name: Create server.xml
  template:
    src: server.xml.j2
    dest: /opt/atlassian-confluence-{{ confluence_version }}/conf/server.xml
    owner: root
    group: confluence
    mode: 0640
  notify: Restart confluence service

- name: Symlink logs directory
  file:
    path: /opt/atlassian-confluence-{{ confluence_version }}/logs
    state: link
    src: /var/log/confluence
    force: true
    owner: confluence
    group: confluence
  notify: Restart confluence service

- name: Set home directory
  copy:
    dest: /opt/atlassian-confluence-{{ confluence_version }}/confluence/WEB-INF/classes/confluence-init.properties
    content: "# Ansible managed - do not edit here!\nconfluence.home=/var/lib/confluence\n"
  notify: Restart confluence service

- name: Set Java options
  copy:
    dest: /etc/default/confluence
    content: "# Ansible managed - do not edit here!\nJAVA_OPTS='{{ confluence_java_opts }}'\n"
  notify: Restart confluence service

- include_tasks: postgresql.yml
  when: confluence_configure_postgres

- name: Create systemd unit
  template:
    src: confluence.service.j2
    dest: /etc/systemd/system/confluence.service
    owner: root
    group: root
    mode: 0644
  notify:
    - Reload systemd configuration
    - Restart confluence service

- meta: flush_handlers

- name: Enable and start
  systemd:
    name: confluence.service
    state: started
    enabled: true
